### ISSUE TITLE
Request for Attribution/Reference for Smart-Resume-Analyzer Project[Original source of this Project]

### ISSUE THREAD

**Issue by Spidy20** [deepakpadhi986/AI-Resume-Analyzer#6]
Hello Deepak,

Approximately two years ago **(on March 6, 2022)**, I created the **Smart-Resume-Analyzer** project. I uploaded it to [GitHub](https://github.com/Spidy20/Smart_Resume_Analyser_App) and also created a tutorial video on YouTube, which comprehensively explains the project. Recently, some subscribers have reached out to me, expressing concerns that you may be using my repository code or projects and distributing them commercially.

I want to clarify that I don't have any issues with this usage. However, what I do expect is proper credit given to me. Upon reviewing your code, I've noticed few codes and scripts, everything that I can see is similar to my repository, and I can see that you created this repository around at 26th September, 2022).

I hope you can empathize with my perspective on this matter. I don't mind if you are profiting from and selling my work, but it's essential to provide some acknowledgment to me. Several subscribers have contacted me previously about this, but I chose to overlook it. However, upon learning that you are using it commercially and selling it without crediting me, I felt compelled to reach out.

Please feel free to get in touch with me. I'm not here to engage in a dispute with you but simply to request that you respect the open-source community.

Regards,
Kushal Bhavsar

**Comment by deepakpadhi986** [comment]
Dear Kushal Bhavsar,

Thank you for reaching out and bringing this matter to my attention. I truly appreciate your understanding and openness in this situation.

Regarding the origins of the project, it was not directly sourced from your YouTube channel but was undertaken under the guidance of Dr. Bright, a Data Scientist, through a course that is unfortunately no longer available. I have explicit permission to use and modify the materials from that course. I have also credited Dr. Bright in my repository to acknowledge their contributions.

In terms of commercial use, I want to clarify that I haven't charged any individual for access to the project. Instead, I've provided assistance to over 60+ students personally through various platforms like Zoom, AnyDesk, and Google Meet. Additionally, I've responded to over 300+ emails requesting project reports and have helped resolve issues for many students through chats on WhatsApp and other social media platforms.

While I acknowledge your concerns about the video tutorial, I want to highlight that simply explaining the project's workings and reading out the code may not suffice in addressing all potential issues. Technology evolves, and new challenges may arise. However, I have continuously updated the project to address these challenges and have provided proper documentation and an installation video to assist users in getting started.

I believe that rather than downgrading or attributing blame, it's essential for both of us to focus on improving our contributions to the community. I've actively contributed to the project by resolving recent issues till now and with proper credit to the references used.

If you require further clarification or evidence, please feel free to reach out to me via email at dnoobnerd@gmail.com.

Thank you for your understanding.

Best regards,
Deepak
